mylist=[]
print(f"{mylist}")
print(type(mylist))
mylist=[10,20,30,"hello"]
print(mylist)
print(mylist[0],mylist[3])
mylist.append("abcd")
print(mylist)
var="devops"
mylist.insert(2,var)
print(mylist)
mylist1=[40,50,60]
mylist.extend(mylist1)
print(mylist)
mylist.pop()
print(mylist)
mylist.pop(4)
print(mylist)
