import re
emaildata="abcd <abcd@gmail.com>, abcdef <abcdef@gmail.com>, abcdefgh <abcdefg@gmail.com>, abcd.efghj <abcd.efghj@gmail.com>"
result=re.search(r"abcd",emaildata)
print(result)
result=re.findall(r"abcd",emaildata)
print(result)
result=re.search(r"AbcD",emaildata,re.IGNORECASE)
print(result)
result=re.search(r"abcd[a,e]",emaildata)
print(result)
result=re.search(r"abcd[a-z]",emaildata)
print(result)
result=re.search(r"abcd[a-z]{2}",emaildata)
print(result)
result=re.search(r"abcd[a-z]+",emaildata)
print(result)
result=re.search(r"[a-zA-Z0-9_]+@[a-zA-Z]+\.[a-zA-Z]+",emaildata)
print(result)
result=re.search(r"\w+@\w+\.\w+",emaildata)
print(result)
result=re.findall(r"\w+@\w+\.\w+",emaildata)
print(result)
